### ISSUE TITLE
Do this same thing with Eleventy

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/github-pages-template#113]
# Blockers

- [ ] ALL other issues are done first.

# Work plan

- [ ] Copy progress in this repo to https://github.com/fulldecent/github-pages-eleventy-template/blob/main/README.md.
- [ ] Do the same thing using Eleventy instead of Jekyll.
- [ ] Explain the justification of using Eleventy vs. Jekyll in the README here and the README there.
- [ ] Burn-in test by applying the best practices learned here to the RNMobility website, which uses GitHub Pages for hosting) and is a simple project without data files or complicated templates.
- [ ] Release version 1.0.0 of this project.
- [ ] Implement these best practices on ACLS Training Center. This is a more complicated installation and will test our knowledge of getting things done in Eleventy!
- [ ] Implement these best practices on all other sites. Let's go! Now we are done with Ruby and Jekyll forever!
