### ISSUE TITLE
Allow to skip testing for URLs

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/github-pages-template#72]
Automated testing for twitter.com always fails.

Let's find a way to skip this an other URLs as needed:

# Work plan

- [x] Add file tests/skip-urls.regex.txt
  - [x] Add https://dont-check-this.example.com
  - [x] Add https://.*.twitter.com/.*
- [x] Load and use this file from plugin.html-validate.external-links.mjs
- [x] Add a test fixture with link to https://dont-check-this.example.com and ensure it is not fetched

**Comment by fulldecent** [comment]
Please add a new test so you can see if this feature is actually working

**Comment by Raza403** [comment]
OK, I added this one in external links test.

**Comment by fulldecent** [comment]
This is deployed
